### PR TITLE
Add basic docs to show on Pulp website

### PR DESCRIPTION
**Pull request by pedro-psb**
Hey @himdel and @ZitaNemeckova !

I'm just adding the basic structure to this.
Along with [this pulp-docs PR,](https://github.com/pulp/pulp-docs/pull/92) it will make pulp-ui `README.md` (relative symlink) to show in the documentation website under `https://pulpproject.org/pulp-ui/`. To stop publishing it, just revert that in `pulp-docs`.

If you decide to setup some changelog tool, pulp-docs will add a `CHANGES.md` (expected to be in the root) to the docs.

I guess because the UI is supposed to be intuitive, you might not need too much docs, but if you want you can create specific docs under `docs/users/`, `docs/admin/` or `docs/dev/` to address specific audiences.

The new docs also proposes using [diataxis](https://diataxis.fr/) categories to help organize the purpose of some content (e.g [in pulpcore](https://github.com/pulp/pulpcore/tree/main/docs)).

Anyway, you can ping me for any doc-related stuff!

### CODE REVIEW

**Review by himdel — APPROVED** [review]

**Comment by himdel** [comment]
Sounds great, thanks! :) 

Right now, the only changelog we have is the autogenerated one in https://github.com/pulp/pulp-ui/releases,
but I suspect we may need to filter out dependabot PRs from the list for it to be really useful as a changelog,
maybe also set up some category labels and filter out changes invisible to users...

And good tips, I suspect docs may take a while yet to evolve, but I expect we'll have to document things once we start trying to support different forms of authentication and such :).

**Comment by pedro-psb** [comment]
> Right now, the only changelog we have is the autogenerated one in https://github.com/pulp/pulp-ui/releases,
but I suspect we may need to filter out dependabot PRs from the list for it to be really useful as a changelog,
maybe also set up some category labels and filter out changes invisible to users...

We use towncrier for that in pulp plugins. Basically you create a changes-file like `CHANGES/123.bugfix`, which is `{associated-issue}.{category}`) and write a user-friendly message there. The advantage is that we already have config/scripts for that.

There are also entirely commit-based tools which looks simple to setup and use, like https://git-cliff.org/. There might be some js packges too.

I can work on this when when we decide what technology to use.

**Comment by himdel** [comment]
Well, towncrier is too heavy-handed, I don't think we should rely on people manually creating `CHANGES/*` files,
but we can try looking for a git based tool that doesn't require special commit message formats :).

What format of `CHANGES.md` do you actually need? (What does it split the versions on? Is it `\n\n----\n`?)

**Comment by himdel** [comment]
Maybe something like https://github.com/pulp/pulp-ui/pull/114 would work for CHANGES.md for now?

**Comment by pedro-psb** [comment]
I will respond there

**Pull request merged**
