### PR TITLE
Add a Dockerfile

### PR DESCRIPTION
**Pull request by gerrod3**
Based on https://github.com/ansible/ansible-hub-ui/blob/master/Dockerfile

### CODE REVIEW

**Comment by himdel** [comment]
Curious why is it needed to have a pulp-ui container running inside oci-env?
(As in, why not just run oci-env for pulp backend, and have the UI just proxy there?)

If you're copying the galaxy ui profile, I'm not sure anyone was using it, there may be skeletons there I don't know about :).

But, looks good as long as it still works :+1:  :)

**Comment by gerrod3** [comment]
> Curious why is it needed to have a pulp-ui container running inside oci-env? (As in, why not just run oci-env for pulp backend, and have the UI just proxy there?)

The eventual goal is to have the UI also run in the same image of the Pulp backend, but I would like to get the node/npm depedencies inside the base Pulp image first. This is a temporary measure to help others on the Pulp team quickly setup the UI if they don't have node install on their system.

**Review by himdel — APPROVED** [review]

**Comment by himdel** [comment]
Ah, makes sense :)

Looks like the Dockerfile should work, as long as it's run with a volume mounted in `/pulp/app` that points to `pulp-ui/`

**Comment by mdellweg** [comment]
> > Curious why is it needed to have a pulp-ui container running inside oci-env? (As in, why not just run oci-env for pulp backend, and have the UI just proxy there?)
> 
> The eventual goal is to have the UI also run in the same image of the Pulp backend, but I would like to get the node/npm depedencies inside the base Pulp image first. This is a temporary measure to help others on the Pulp team quickly setup the UI if they don't have node install on their system.

Honestly, I would prefer to not install node in the ci-container. It is still the base image for all the "production ready" containers we ship. And in production, you "just" want to serve some static files along with the API.

**Comment by gerrod3** [comment]
> Honestly, I would prefer to not install node in the ci-container. It is still the base image for all the "production ready" containers we ship. And in production, you "just" want to serve some static files along with the API.

Yes, after the UI meeting I am in agreement that we just want the images to serve the static files. I'll make the changes to the oci-images CI to build the files and copy them over to the image.

**Pull request merged**
